---
title: "CARE secondary parotid tumours"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
pacman::p_load(tidyverse, 
               gtsummary,
               dlookr, 
               janitor)
```

For wordcloud

```{r}
pacman::p_load(wordcloud, # word-cloud generator 
               SnowballC, # for text stemming
               RColorBrewer, # palette
               wordcloud2, 
               tm) # for text mining
```

```{r}
theme_set(theme_minimal())
```

# Dataset

```{r}
df <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRKPzFe2lbF87DNe9SBjuaIb5iMb4nCmgvfdyT4v-NjK-BZBR-HkUIUdgiML3t30EqQ1RCep0sExatK/pub?output=csv")
```

```{r}
names(df)
```

```{r}
dlookr::diagnose(df)
```

```{r}
df <- df %>%
  mutate(JOURNAL = str_to_title(JOURNAL)) %>% # change the capitalization
  mutate(JOURNAL = str_trim(JOURNAL, side = c("both"))) %>% # remove spaces
  mutate(JOURNAL = str_replace(JOURNAL, "Resaerch", "Research")) 
```

# EDA

How many papers

```{r}
n_distinct(df$TITLE)
```

From how many journals?

```{r}
n_distinct(df$JOURNAL)
```

Patients

```{r}
df %>% 
  ggplot(aes(x = `Number of patients`)) + 
  geom_histogram(bins = 6)
```

How many patients

```{r}
summary(df$`Number of patients`)
```

Males and females

```{r}
df %>% 
  pivot_longer(`Males reported`:`Females reported`, 
               names_to = "sex", 
               values_to = "sex_values") %>% 
  ggplot(aes(x = sex_values, 
             fill = "sex")) + 
               
  geom_histogram(bins = 6) + 
  facet_grid(sex ~ .)
```

Year of publication

```{r}
df %>% 
  ggplot(aes(x = `YEAR published`)) + 
  geom_histogram(bins = 10)
```

Age of the patients

```{r}
df %>% 
  ggplot(aes(Age)) + 
  geom_histogram(bins = 10)
```

Age of the patients by sex

```{r}
df %>% 
  pivot_longer(`Males reported`:`Females reported`, 
               names_to = "sex", 
               values_to = "sex_values") %>% 
  ggplot(aes(y = sex_values, 
             x = Age, 
             color = sex)) + 
  geom_jitter(alpha = .7) + 
  facet_grid(sex ~ . )
```

```{r}
df %>% 
  pivot_longer(`Males reported`:`Females reported`, 
               names_to = "sex", 
               values_to = "sex_values") %>% 
  ggplot(aes(y = Age, 
             x = sex, 
             color = sex)) + 
  geom_boxplot(alpha = .7) + 
  geom_jitter(alpha = .2, width = .2)
```

# Wordcloud

```{r}
text <- df$`Copy and paste the abstract`
docs <- Corpus(VectorSource(text))
```

```{r}
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
```

```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("keywords")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```

```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```

```{r}
set.seed(1234)
wordcloud(
  words = d$word,
  freq = d$freq,
  min.freq = 35,
  max.words = 200,
  random.order = TRUE,
  rot.per = 0.35,
  colors = brewer.pal(8, "Dark2")
)
```

```{r}
findFreqTerms(dtm, lowfreq = 4)
```

```{r}
findAssocs(dtm, terms = "primary", corlimit = 0.4)
```

```{r}
df %>% 
  tabyl(Reviewer)
```

# Ingus 1 march 2022

I: Agreement between Ingus and Peteris

S: what is the quality of the reports?

I: what is the quality before and after 2015

I: difference between journals
